"""
guardian/ai_playbook.py
-----------------------
OpenAI streaming integration.  Sends the current digital-twin state,
live weather telemetry, and Scikit-Learn probability scores to the
chosen model and yields response chunks for Streamlit's live display.

Public API
----------
stream_playbook(api_key, city_state, weather_params, ml_label,
                ml_probs, ml_label_name, city_name, model)
    -> Generator[str, None, None]  – yields text chunks
"""

import json
from openai import OpenAI


# ── Prompt templates ────────────────────────────────────────────────────────

_SYSTEM_PROMPT = (
    "You are the central autonomous AI brain of a high-tech smart-city "
    "digital twin. "
    "Your purpose is to analyze a disaster risk probability generated by a "
    "Scikit-Learn Random Forest machine learning model, along with live "
    "structural telemetry of the city's digital twin during a disaster, and "
    "instantly execute preliminary precautions, infrastructure mitigation, "
    "resource allocation, and civil defense automation strategies. "
    "Be structured, authoritative, action-oriented, and write in clear "
    "markdown formatting. Do not use legacy markdown that breaks Streamlit "
    "rendering. Keep responses concise and focused on high-impact steps."
)

_USER_PROMPT_TEMPLATE = """\
=== SELECTED CITY ===
{city_name}

=== SCIKIT-LEARN ML MODEL OUTPUT ===
Predicted Risk Label : {ml_label} – {ml_label_name}
Probability Scores   :
  • P(Normal)                      = {p_normal:.1%}
  • P(Flash Flood Risk)            = {p_flood:.1%}
  • P(Heatwave / Wildfire Risk)    = {p_heat:.1%}
  • P(Drought / Water Scarcity)    = {p_drought:.1%}
  • P(Heavy Snow / Blizzard)       = {p_snow:.1%}

=== LIVE WEATHER TELEMETRY (Sensor Input) ===
  • Temperature        : {temp}°C
  • Humidity           : {humidity}%
  • Wind Speed         : {wind_speed} km/h
  • Barometric Pressure: {pressure} hPa
  • Current Precipitation: {precipitation} mm
  • Current Snowfall     : {snowfall} cm
  • Snow Depth           : {snow_depth} m
  • Surface Soil Moisture: {soil_moisture} m³/m³

=== CITY DIGITAL TWIN – CURRENT MOCK INFRASTRUCTURE STATUS ===
{state_json}

---
Based on the above ML prediction probabilities and the live infrastructure \
status of {city_name}, generate a structured **Autonomous \
Preliminary Precaution & Critical Mitigation Playbook** covering:

1. **Automated Infrastructure Changes** \
(power load shedding, sluice gate automation, grid failover commands)
2. **Emergency Resource Dispatch** \
(depot routing, fleet pre-positioning, hospital surge alerts)
3. **Automated Civil Broadcast** \
(localized emergency broadcast scripts referencing {city_name} and the \
mock infrastructure nodes supplied in the digital-twin status)
"""


# ── Public streaming generator ───────────────────────────────────────────────

def stream_playbook(
    api_key: str,
    city_state: dict,
    weather_params: dict,
    ml_label: int,
    ml_probs: list,
    ml_label_name: str,
    city_name: str,
    model: str = "gpt-4o-mini",
):
    """
    Stream the AI mitigation playbook as text chunks.

    Parameters
    ----------
    api_key       : OpenAI secret key
    city_state    : mutated digital-twin dict from crisis_engine
    weather_params: dict with current Open-Meteo sensor values
    ml_label      : int prediction from RandomForestClassifier
    ml_probs      : list of class probabilities [P(0), ..., P(4)]
    ml_label_name : human-readable label string
    city_name     : resolved Open-Meteo city name
    model         : OpenAI model identifier (default: gpt-4o-mini)

    Yields
    ------
    str – successive text chunks from the streaming response
    """
    client = OpenAI(api_key=api_key)

    user_prompt = _USER_PROMPT_TEMPLATE.format(
        city_name=city_name,
        ml_label=ml_label,
        ml_label_name=ml_label_name,
        p_normal=ml_probs[0],
        p_flood=ml_probs[1],
        p_heat=ml_probs[2],
        p_drought=ml_probs[3],
        p_snow=ml_probs[4],
        temp=weather_params["temp"],
        humidity=weather_params["humidity"],
        wind_speed=weather_params["wind_speed"],
        pressure=weather_params["pressure"],
        precipitation=weather_params.get("precipitation", 0.0),
        snowfall=weather_params.get("snowfall", 0.0),
        snow_depth=weather_params.get("snow_depth", 0.0),
        soil_moisture=weather_params.get("soil_moisture", 0.0),
        state_json=json.dumps(city_state, indent=2),
    )

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user",   "content": user_prompt},
        ],
        stream=True,
    )

    for chunk in response:
        delta = chunk.choices[0].delta.content
        if delta:
            yield delta
